name: APK Build
on:
  push:

jobs:

  build-android:
    name: Build Android Package
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: app
          buildozer_version: stable
  
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: kvsearch_apk
          path: ${{ steps.buildozer.outputs.filename }}